### ISSUE TITLE
Missing constant for Scale

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/JavaPOSContracts#7]
Constant **SCAL_SUE_WEIGHT_UNDERWEIGHT** missing. This limits service implementors, making it impossible to signal underweight situation to application.

**Comment by kuniss** [comment]
Code and UnifiedPOS specification review showed:
**SCAL_SUE_WEIGHT_UNDERWEIGHT** is lacking in [ScaleConst.java](https://github.com/JavaPOSWorkingGroup/javapos-contracts/blob/9d7e9ccfdf6880410cf23a0e6055cf396f0a8d6d/src/main/java/jpos/ScaleConst.java) but defined in the UnifiedPOS specification for _Scale_'s _StatusUpdateEvent_ since UnifiedPOS release 1.14. So it needs to be added as constant.

**Note:** This is also not defined in OPOS' OposScal.h! The UnifedPOS 1.14 specification is lacking the "Updated in Release 1.14" tag at _Scale_'s _StatusUpdateEvent_ chapter. Maybe therefore, it was not considered, neither in the JavaPOS nor in the [OPOS reference](http://monroecs.com/oposccos.htm) implementations.

Good catch @mjpcger !

**Comment by kuniss** [comment]
Solved with release [1.14.4](https://github.com/JavaPOSWorkingGroup/javapos-contracts/tree/1.14.4).
